// My40.idl: источник библиотеки типов для Перемножение матрицы 4.0.exe

// Этот файл будет обработан компилятором MIDL для создания
// библиотека типов (My40.tlb).

[ uuid(0b636c6a-41ca-4ccb-a339-a845778cbb43), version(1.0) ]
library Перемножениематрицы40
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Первичный интерфейс диспетчеризации для CПеремножениематрицы40Doc

	[ uuid(682ddcdc-26fa-4ab4-86d9-c946423995c1) ]
	dispinterface IПеремножениематрицы40
	{
		properties:

		methods:
	};

	//  Сведения о классе CПеремножениематрицы40Doc

	[ uuid(7ebe73ec-1c3b-4cc1-9904-3fa0b76e6dd9) ]
	coclass Перемножениематрицы40
	{
		[default] dispinterface IПеремножениематрицы40;
	};
};
